version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"
      timezone: "America/Toronto"
    commit-message:
        prefix: "ci(deps): "
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "America/Toronto"
    commit-message:
        prefix: "chore(deps): "
    reviewers:
      - "devcyclehq/engineering"
