/*
 * DevCycle Bucketing API
 * Documents the DevCycle Bucketing API which provides and API interface to User Bucketing and for generated SDKs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.devcycle.sdk.server.common.model;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class DevCycleEvent {

  @Schema(required = true, description = "Custom event type")
  private String type;

  @Schema(description = "Custom event target / subject of event. Contextual to event type")
  private String target;

  @Schema(description = "Unix epoch time the event occurred according to client")
  private Long date;

  @Schema(description = "Value for numerical events. Contextual to event type")
  private BigDecimal value;

  @Schema(description = "Extra JSON metadata for event. Contextual to event type")
  private Object metaData;
}
