// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

/**
 * Protobuf enum {@code CustomDataType}
 */
public enum CustomDataType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Bool = 0;</code>
   */
  Bool(0),
  /**
   * <code>Num = 1;</code>
   */
  Num(1),
  /**
   * <code>Str = 2;</code>
   */
  Str(2),
  /**
   * <code>Null = 3;</code>
   */
  Null(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Bool = 0;</code>
   */
  public static final int Bool_VALUE = 0;
  /**
   * <code>Num = 1;</code>
   */
  public static final int Num_VALUE = 1;
  /**
   * <code>Str = 2;</code>
   */
  public static final int Str_VALUE = 2;
  /**
   * <code>Null = 3;</code>
   */
  public static final int Null_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CustomDataType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CustomDataType forNumber(int value) {
    switch (value) {
      case 0: return Bool;
      case 1: return Num;
      case 2: return Str;
      case 3: return Null;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CustomDataType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CustomDataType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CustomDataType>() {
          public CustomDataType findValueByNumber(int number) {
            return CustomDataType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.getDescriptor().getEnumTypes().get(1);
  }

  private static final CustomDataType[] VALUES = values();

  public static CustomDataType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CustomDataType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:CustomDataType)
}

