// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

/**
 * Protobuf type {@code DVCUser_PB}
 */
public final class DVCUser_PB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DVCUser_PB)
    DVCUser_PBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DVCUser_PB.newBuilder() to construct.
  private DVCUser_PB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DVCUser_PB() {
    userId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DVCUser_PB();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_DVCUser_PB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_DVCUser_PB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.devcycle.sdk.server.local.protobuf.DVCUser_PB.class, com.devcycle.sdk.server.local.protobuf.DVCUser_PB.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 2;
  private com.devcycle.sdk.server.local.protobuf.NullableString email_;
  /**
   * <code>.NullableString email = 2;</code>
   * @return Whether the email field is set.
   */
  @java.lang.Override
  public boolean hasEmail() {
    return email_ != null;
  }
  /**
   * <code>.NullableString email = 2;</code>
   * @return The email.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableString getEmail() {
    return email_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : email_;
  }
  /**
   * <code>.NullableString email = 2;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getEmailOrBuilder() {
    return email_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : email_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private com.devcycle.sdk.server.local.protobuf.NullableString name_;
  /**
   * <code>.NullableString name = 3;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return name_ != null;
  }
  /**
   * <code>.NullableString name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableString getName() {
    return name_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : name_;
  }
  /**
   * <code>.NullableString name = 3;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getNameOrBuilder() {
    return name_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : name_;
  }

  public static final int LANGUAGE_FIELD_NUMBER = 4;
  private com.devcycle.sdk.server.local.protobuf.NullableString language_;
  /**
   * <code>.NullableString language = 4;</code>
   * @return Whether the language field is set.
   */
  @java.lang.Override
  public boolean hasLanguage() {
    return language_ != null;
  }
  /**
   * <code>.NullableString language = 4;</code>
   * @return The language.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableString getLanguage() {
    return language_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : language_;
  }
  /**
   * <code>.NullableString language = 4;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getLanguageOrBuilder() {
    return language_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : language_;
  }

  public static final int COUNTRY_FIELD_NUMBER = 5;
  private com.devcycle.sdk.server.local.protobuf.NullableString country_;
  /**
   * <code>.NullableString country = 5;</code>
   * @return Whether the country field is set.
   */
  @java.lang.Override
  public boolean hasCountry() {
    return country_ != null;
  }
  /**
   * <code>.NullableString country = 5;</code>
   * @return The country.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableString getCountry() {
    return country_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : country_;
  }
  /**
   * <code>.NullableString country = 5;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getCountryOrBuilder() {
    return country_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : country_;
  }

  public static final int APPBUILD_FIELD_NUMBER = 6;
  private com.devcycle.sdk.server.local.protobuf.NullableDouble appBuild_;
  /**
   * <code>.NullableDouble appBuild = 6;</code>
   * @return Whether the appBuild field is set.
   */
  @java.lang.Override
  public boolean hasAppBuild() {
    return appBuild_ != null;
  }
  /**
   * <code>.NullableDouble appBuild = 6;</code>
   * @return The appBuild.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableDouble getAppBuild() {
    return appBuild_ == null ? com.devcycle.sdk.server.local.protobuf.NullableDouble.getDefaultInstance() : appBuild_;
  }
  /**
   * <code>.NullableDouble appBuild = 6;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableDoubleOrBuilder getAppBuildOrBuilder() {
    return appBuild_ == null ? com.devcycle.sdk.server.local.protobuf.NullableDouble.getDefaultInstance() : appBuild_;
  }

  public static final int APPVERSION_FIELD_NUMBER = 7;
  private com.devcycle.sdk.server.local.protobuf.NullableString appVersion_;
  /**
   * <code>.NullableString appVersion = 7;</code>
   * @return Whether the appVersion field is set.
   */
  @java.lang.Override
  public boolean hasAppVersion() {
    return appVersion_ != null;
  }
  /**
   * <code>.NullableString appVersion = 7;</code>
   * @return The appVersion.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableString getAppVersion() {
    return appVersion_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : appVersion_;
  }
  /**
   * <code>.NullableString appVersion = 7;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getAppVersionOrBuilder() {
    return appVersion_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : appVersion_;
  }

  public static final int DEVICEMODEL_FIELD_NUMBER = 8;
  private com.devcycle.sdk.server.local.protobuf.NullableString deviceModel_;
  /**
   * <code>.NullableString deviceModel = 8;</code>
   * @return Whether the deviceModel field is set.
   */
  @java.lang.Override
  public boolean hasDeviceModel() {
    return deviceModel_ != null;
  }
  /**
   * <code>.NullableString deviceModel = 8;</code>
   * @return The deviceModel.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableString getDeviceModel() {
    return deviceModel_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : deviceModel_;
  }
  /**
   * <code>.NullableString deviceModel = 8;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getDeviceModelOrBuilder() {
    return deviceModel_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : deviceModel_;
  }

  public static final int CUSTOMDATA_FIELD_NUMBER = 9;
  private com.devcycle.sdk.server.local.protobuf.NullableCustomData customData_;
  /**
   * <code>.NullableCustomData customData = 9;</code>
   * @return Whether the customData field is set.
   */
  @java.lang.Override
  public boolean hasCustomData() {
    return customData_ != null;
  }
  /**
   * <code>.NullableCustomData customData = 9;</code>
   * @return The customData.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableCustomData getCustomData() {
    return customData_ == null ? com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance() : customData_;
  }
  /**
   * <code>.NullableCustomData customData = 9;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder getCustomDataOrBuilder() {
    return customData_ == null ? com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance() : customData_;
  }

  public static final int PRIVATECUSTOMDATA_FIELD_NUMBER = 10;
  private com.devcycle.sdk.server.local.protobuf.NullableCustomData privateCustomData_;
  /**
   * <code>.NullableCustomData privateCustomData = 10;</code>
   * @return Whether the privateCustomData field is set.
   */
  @java.lang.Override
  public boolean hasPrivateCustomData() {
    return privateCustomData_ != null;
  }
  /**
   * <code>.NullableCustomData privateCustomData = 10;</code>
   * @return The privateCustomData.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableCustomData getPrivateCustomData() {
    return privateCustomData_ == null ? com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance() : privateCustomData_;
  }
  /**
   * <code>.NullableCustomData privateCustomData = 10;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder getPrivateCustomDataOrBuilder() {
    return privateCustomData_ == null ? com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance() : privateCustomData_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (email_ != null) {
      output.writeMessage(2, getEmail());
    }
    if (name_ != null) {
      output.writeMessage(3, getName());
    }
    if (language_ != null) {
      output.writeMessage(4, getLanguage());
    }
    if (country_ != null) {
      output.writeMessage(5, getCountry());
    }
    if (appBuild_ != null) {
      output.writeMessage(6, getAppBuild());
    }
    if (appVersion_ != null) {
      output.writeMessage(7, getAppVersion());
    }
    if (deviceModel_ != null) {
      output.writeMessage(8, getDeviceModel());
    }
    if (customData_ != null) {
      output.writeMessage(9, getCustomData());
    }
    if (privateCustomData_ != null) {
      output.writeMessage(10, getPrivateCustomData());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (email_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEmail());
    }
    if (name_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getName());
    }
    if (language_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLanguage());
    }
    if (country_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCountry());
    }
    if (appBuild_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getAppBuild());
    }
    if (appVersion_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getAppVersion());
    }
    if (deviceModel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getDeviceModel());
    }
    if (customData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getCustomData());
    }
    if (privateCustomData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getPrivateCustomData());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.devcycle.sdk.server.local.protobuf.DVCUser_PB)) {
      return super.equals(obj);
    }
    com.devcycle.sdk.server.local.protobuf.DVCUser_PB other = (com.devcycle.sdk.server.local.protobuf.DVCUser_PB) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
          .equals(other.getEmail())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasLanguage() != other.hasLanguage()) return false;
    if (hasLanguage()) {
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
    }
    if (hasCountry() != other.hasCountry()) return false;
    if (hasCountry()) {
      if (!getCountry()
          .equals(other.getCountry())) return false;
    }
    if (hasAppBuild() != other.hasAppBuild()) return false;
    if (hasAppBuild()) {
      if (!getAppBuild()
          .equals(other.getAppBuild())) return false;
    }
    if (hasAppVersion() != other.hasAppVersion()) return false;
    if (hasAppVersion()) {
      if (!getAppVersion()
          .equals(other.getAppVersion())) return false;
    }
    if (hasDeviceModel() != other.hasDeviceModel()) return false;
    if (hasDeviceModel()) {
      if (!getDeviceModel()
          .equals(other.getDeviceModel())) return false;
    }
    if (hasCustomData() != other.hasCustomData()) return false;
    if (hasCustomData()) {
      if (!getCustomData()
          .equals(other.getCustomData())) return false;
    }
    if (hasPrivateCustomData() != other.hasPrivateCustomData()) return false;
    if (hasPrivateCustomData()) {
      if (!getPrivateCustomData()
          .equals(other.getPrivateCustomData())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasLanguage()) {
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
    }
    if (hasCountry()) {
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
    }
    if (hasAppBuild()) {
      hash = (37 * hash) + APPBUILD_FIELD_NUMBER;
      hash = (53 * hash) + getAppBuild().hashCode();
    }
    if (hasAppVersion()) {
      hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersion().hashCode();
    }
    if (hasDeviceModel()) {
      hash = (37 * hash) + DEVICEMODEL_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceModel().hashCode();
    }
    if (hasCustomData()) {
      hash = (37 * hash) + CUSTOMDATA_FIELD_NUMBER;
      hash = (53 * hash) + getCustomData().hashCode();
    }
    if (hasPrivateCustomData()) {
      hash = (37 * hash) + PRIVATECUSTOMDATA_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateCustomData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.devcycle.sdk.server.local.protobuf.DVCUser_PB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DVCUser_PB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DVCUser_PB)
      com.devcycle.sdk.server.local.protobuf.DVCUser_PBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_DVCUser_PB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_DVCUser_PB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.devcycle.sdk.server.local.protobuf.DVCUser_PB.class, com.devcycle.sdk.server.local.protobuf.DVCUser_PB.Builder.class);
    }

    // Construct using com.devcycle.sdk.server.local.protobuf.DVCUser_PB.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = "";
      email_ = null;
      if (emailBuilder_ != null) {
        emailBuilder_.dispose();
        emailBuilder_ = null;
      }
      name_ = null;
      if (nameBuilder_ != null) {
        nameBuilder_.dispose();
        nameBuilder_ = null;
      }
      language_ = null;
      if (languageBuilder_ != null) {
        languageBuilder_.dispose();
        languageBuilder_ = null;
      }
      country_ = null;
      if (countryBuilder_ != null) {
        countryBuilder_.dispose();
        countryBuilder_ = null;
      }
      appBuild_ = null;
      if (appBuildBuilder_ != null) {
        appBuildBuilder_.dispose();
        appBuildBuilder_ = null;
      }
      appVersion_ = null;
      if (appVersionBuilder_ != null) {
        appVersionBuilder_.dispose();
        appVersionBuilder_ = null;
      }
      deviceModel_ = null;
      if (deviceModelBuilder_ != null) {
        deviceModelBuilder_.dispose();
        deviceModelBuilder_ = null;
      }
      customData_ = null;
      if (customDataBuilder_ != null) {
        customDataBuilder_.dispose();
        customDataBuilder_ = null;
      }
      privateCustomData_ = null;
      if (privateCustomDataBuilder_ != null) {
        privateCustomDataBuilder_.dispose();
        privateCustomDataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_DVCUser_PB_descriptor;
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.DVCUser_PB getDefaultInstanceForType() {
      return com.devcycle.sdk.server.local.protobuf.DVCUser_PB.getDefaultInstance();
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.DVCUser_PB build() {
      com.devcycle.sdk.server.local.protobuf.DVCUser_PB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.DVCUser_PB buildPartial() {
      com.devcycle.sdk.server.local.protobuf.DVCUser_PB result = new com.devcycle.sdk.server.local.protobuf.DVCUser_PB(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.devcycle.sdk.server.local.protobuf.DVCUser_PB result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.email_ = emailBuilder_ == null
            ? email_
            : emailBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = nameBuilder_ == null
            ? name_
            : nameBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.language_ = languageBuilder_ == null
            ? language_
            : languageBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.country_ = countryBuilder_ == null
            ? country_
            : countryBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.appBuild_ = appBuildBuilder_ == null
            ? appBuild_
            : appBuildBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.appVersion_ = appVersionBuilder_ == null
            ? appVersion_
            : appVersionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.deviceModel_ = deviceModelBuilder_ == null
            ? deviceModel_
            : deviceModelBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.customData_ = customDataBuilder_ == null
            ? customData_
            : customDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.privateCustomData_ = privateCustomDataBuilder_ == null
            ? privateCustomData_
            : privateCustomDataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.devcycle.sdk.server.local.protobuf.DVCUser_PB) {
        return mergeFrom((com.devcycle.sdk.server.local.protobuf.DVCUser_PB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.devcycle.sdk.server.local.protobuf.DVCUser_PB other) {
      if (other == com.devcycle.sdk.server.local.protobuf.DVCUser_PB.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasEmail()) {
        mergeEmail(other.getEmail());
      }
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (other.hasLanguage()) {
        mergeLanguage(other.getLanguage());
      }
      if (other.hasCountry()) {
        mergeCountry(other.getCountry());
      }
      if (other.hasAppBuild()) {
        mergeAppBuild(other.getAppBuild());
      }
      if (other.hasAppVersion()) {
        mergeAppVersion(other.getAppVersion());
      }
      if (other.hasDeviceModel()) {
        mergeDeviceModel(other.getDeviceModel());
      }
      if (other.hasCustomData()) {
        mergeCustomData(other.getCustomData());
      }
      if (other.hasPrivateCustomData()) {
        mergePrivateCustomData(other.getPrivateCustomData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getEmailFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getLanguageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getCountryFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getAppBuildFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getAppVersionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getDeviceModelFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getCustomDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getPrivateCustomDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableString email_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> emailBuilder_;
    /**
     * <code>.NullableString email = 2;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.NullableString email = 2;</code>
     * @return The email.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString getEmail() {
      if (emailBuilder_ == null) {
        return email_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : email_;
      } else {
        return emailBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableString email = 2;</code>
     */
    public Builder setEmail(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (emailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        email_ = value;
      } else {
        emailBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString email = 2;</code>
     */
    public Builder setEmail(
        com.devcycle.sdk.server.local.protobuf.NullableString.Builder builderForValue) {
      if (emailBuilder_ == null) {
        email_ = builderForValue.build();
      } else {
        emailBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString email = 2;</code>
     */
    public Builder mergeEmail(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (emailBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          email_ != null &&
          email_ != com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance()) {
          getEmailBuilder().mergeFrom(value);
        } else {
          email_ = value;
        }
      } else {
        emailBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString email = 2;</code>
     */
    public Builder clearEmail() {
      bitField0_ = (bitField0_ & ~0x00000002);
      email_ = null;
      if (emailBuilder_ != null) {
        emailBuilder_.dispose();
        emailBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString email = 2;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString.Builder getEmailBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getEmailFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableString email = 2;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getEmailOrBuilder() {
      if (emailBuilder_ != null) {
        return emailBuilder_.getMessageOrBuilder();
      } else {
        return email_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : email_;
      }
    }
    /**
     * <code>.NullableString email = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> 
        getEmailFieldBuilder() {
      if (emailBuilder_ == null) {
        emailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder>(
                getEmail(),
                getParentForChildren(),
                isClean());
        email_ = null;
      }
      return emailBuilder_;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableString name_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> nameBuilder_;
    /**
     * <code>.NullableString name = 3;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.NullableString name = 3;</code>
     * @return The name.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableString name = 3;</code>
     */
    public Builder setName(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
      } else {
        nameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString name = 3;</code>
     */
    public Builder setName(
        com.devcycle.sdk.server.local.protobuf.NullableString.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString name = 3;</code>
     */
    public Builder mergeName(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (nameBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          name_ != null &&
          name_ != com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance()) {
          getNameBuilder().mergeFrom(value);
        } else {
          name_ = value;
        }
      } else {
        nameBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString name = 3;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      name_ = null;
      if (nameBuilder_ != null) {
        nameBuilder_.dispose();
        nameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString name = 3;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString.Builder getNameBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableString name = 3;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.NullableString name = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableString language_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> languageBuilder_;
    /**
     * <code>.NullableString language = 4;</code>
     * @return Whether the language field is set.
     */
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.NullableString language = 4;</code>
     * @return The language.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString getLanguage() {
      if (languageBuilder_ == null) {
        return language_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : language_;
      } else {
        return languageBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableString language = 4;</code>
     */
    public Builder setLanguage(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (languageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        language_ = value;
      } else {
        languageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString language = 4;</code>
     */
    public Builder setLanguage(
        com.devcycle.sdk.server.local.protobuf.NullableString.Builder builderForValue) {
      if (languageBuilder_ == null) {
        language_ = builderForValue.build();
      } else {
        languageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString language = 4;</code>
     */
    public Builder mergeLanguage(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (languageBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          language_ != null &&
          language_ != com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance()) {
          getLanguageBuilder().mergeFrom(value);
        } else {
          language_ = value;
        }
      } else {
        languageBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString language = 4;</code>
     */
    public Builder clearLanguage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      language_ = null;
      if (languageBuilder_ != null) {
        languageBuilder_.dispose();
        languageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString language = 4;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString.Builder getLanguageBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getLanguageFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableString language = 4;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getLanguageOrBuilder() {
      if (languageBuilder_ != null) {
        return languageBuilder_.getMessageOrBuilder();
      } else {
        return language_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : language_;
      }
    }
    /**
     * <code>.NullableString language = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> 
        getLanguageFieldBuilder() {
      if (languageBuilder_ == null) {
        languageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder>(
                getLanguage(),
                getParentForChildren(),
                isClean());
        language_ = null;
      }
      return languageBuilder_;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableString country_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> countryBuilder_;
    /**
     * <code>.NullableString country = 5;</code>
     * @return Whether the country field is set.
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.NullableString country = 5;</code>
     * @return The country.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString getCountry() {
      if (countryBuilder_ == null) {
        return country_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : country_;
      } else {
        return countryBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableString country = 5;</code>
     */
    public Builder setCountry(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (countryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        country_ = value;
      } else {
        countryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString country = 5;</code>
     */
    public Builder setCountry(
        com.devcycle.sdk.server.local.protobuf.NullableString.Builder builderForValue) {
      if (countryBuilder_ == null) {
        country_ = builderForValue.build();
      } else {
        countryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString country = 5;</code>
     */
    public Builder mergeCountry(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (countryBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          country_ != null &&
          country_ != com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance()) {
          getCountryBuilder().mergeFrom(value);
        } else {
          country_ = value;
        }
      } else {
        countryBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString country = 5;</code>
     */
    public Builder clearCountry() {
      bitField0_ = (bitField0_ & ~0x00000010);
      country_ = null;
      if (countryBuilder_ != null) {
        countryBuilder_.dispose();
        countryBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString country = 5;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString.Builder getCountryBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getCountryFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableString country = 5;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getCountryOrBuilder() {
      if (countryBuilder_ != null) {
        return countryBuilder_.getMessageOrBuilder();
      } else {
        return country_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : country_;
      }
    }
    /**
     * <code>.NullableString country = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> 
        getCountryFieldBuilder() {
      if (countryBuilder_ == null) {
        countryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder>(
                getCountry(),
                getParentForChildren(),
                isClean());
        country_ = null;
      }
      return countryBuilder_;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableDouble appBuild_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableDouble, com.devcycle.sdk.server.local.protobuf.NullableDouble.Builder, com.devcycle.sdk.server.local.protobuf.NullableDoubleOrBuilder> appBuildBuilder_;
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     * @return Whether the appBuild field is set.
     */
    public boolean hasAppBuild() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     * @return The appBuild.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableDouble getAppBuild() {
      if (appBuildBuilder_ == null) {
        return appBuild_ == null ? com.devcycle.sdk.server.local.protobuf.NullableDouble.getDefaultInstance() : appBuild_;
      } else {
        return appBuildBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     */
    public Builder setAppBuild(com.devcycle.sdk.server.local.protobuf.NullableDouble value) {
      if (appBuildBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        appBuild_ = value;
      } else {
        appBuildBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     */
    public Builder setAppBuild(
        com.devcycle.sdk.server.local.protobuf.NullableDouble.Builder builderForValue) {
      if (appBuildBuilder_ == null) {
        appBuild_ = builderForValue.build();
      } else {
        appBuildBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     */
    public Builder mergeAppBuild(com.devcycle.sdk.server.local.protobuf.NullableDouble value) {
      if (appBuildBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          appBuild_ != null &&
          appBuild_ != com.devcycle.sdk.server.local.protobuf.NullableDouble.getDefaultInstance()) {
          getAppBuildBuilder().mergeFrom(value);
        } else {
          appBuild_ = value;
        }
      } else {
        appBuildBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     */
    public Builder clearAppBuild() {
      bitField0_ = (bitField0_ & ~0x00000020);
      appBuild_ = null;
      if (appBuildBuilder_ != null) {
        appBuildBuilder_.dispose();
        appBuildBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableDouble.Builder getAppBuildBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getAppBuildFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableDoubleOrBuilder getAppBuildOrBuilder() {
      if (appBuildBuilder_ != null) {
        return appBuildBuilder_.getMessageOrBuilder();
      } else {
        return appBuild_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableDouble.getDefaultInstance() : appBuild_;
      }
    }
    /**
     * <code>.NullableDouble appBuild = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableDouble, com.devcycle.sdk.server.local.protobuf.NullableDouble.Builder, com.devcycle.sdk.server.local.protobuf.NullableDoubleOrBuilder> 
        getAppBuildFieldBuilder() {
      if (appBuildBuilder_ == null) {
        appBuildBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableDouble, com.devcycle.sdk.server.local.protobuf.NullableDouble.Builder, com.devcycle.sdk.server.local.protobuf.NullableDoubleOrBuilder>(
                getAppBuild(),
                getParentForChildren(),
                isClean());
        appBuild_ = null;
      }
      return appBuildBuilder_;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableString appVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> appVersionBuilder_;
    /**
     * <code>.NullableString appVersion = 7;</code>
     * @return Whether the appVersion field is set.
     */
    public boolean hasAppVersion() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.NullableString appVersion = 7;</code>
     * @return The appVersion.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString getAppVersion() {
      if (appVersionBuilder_ == null) {
        return appVersion_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : appVersion_;
      } else {
        return appVersionBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableString appVersion = 7;</code>
     */
    public Builder setAppVersion(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (appVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        appVersion_ = value;
      } else {
        appVersionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString appVersion = 7;</code>
     */
    public Builder setAppVersion(
        com.devcycle.sdk.server.local.protobuf.NullableString.Builder builderForValue) {
      if (appVersionBuilder_ == null) {
        appVersion_ = builderForValue.build();
      } else {
        appVersionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString appVersion = 7;</code>
     */
    public Builder mergeAppVersion(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (appVersionBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          appVersion_ != null &&
          appVersion_ != com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance()) {
          getAppVersionBuilder().mergeFrom(value);
        } else {
          appVersion_ = value;
        }
      } else {
        appVersionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString appVersion = 7;</code>
     */
    public Builder clearAppVersion() {
      bitField0_ = (bitField0_ & ~0x00000040);
      appVersion_ = null;
      if (appVersionBuilder_ != null) {
        appVersionBuilder_.dispose();
        appVersionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString appVersion = 7;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString.Builder getAppVersionBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getAppVersionFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableString appVersion = 7;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getAppVersionOrBuilder() {
      if (appVersionBuilder_ != null) {
        return appVersionBuilder_.getMessageOrBuilder();
      } else {
        return appVersion_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : appVersion_;
      }
    }
    /**
     * <code>.NullableString appVersion = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> 
        getAppVersionFieldBuilder() {
      if (appVersionBuilder_ == null) {
        appVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder>(
                getAppVersion(),
                getParentForChildren(),
                isClean());
        appVersion_ = null;
      }
      return appVersionBuilder_;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableString deviceModel_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> deviceModelBuilder_;
    /**
     * <code>.NullableString deviceModel = 8;</code>
     * @return Whether the deviceModel field is set.
     */
    public boolean hasDeviceModel() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.NullableString deviceModel = 8;</code>
     * @return The deviceModel.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString getDeviceModel() {
      if (deviceModelBuilder_ == null) {
        return deviceModel_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : deviceModel_;
      } else {
        return deviceModelBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableString deviceModel = 8;</code>
     */
    public Builder setDeviceModel(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (deviceModelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deviceModel_ = value;
      } else {
        deviceModelBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString deviceModel = 8;</code>
     */
    public Builder setDeviceModel(
        com.devcycle.sdk.server.local.protobuf.NullableString.Builder builderForValue) {
      if (deviceModelBuilder_ == null) {
        deviceModel_ = builderForValue.build();
      } else {
        deviceModelBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString deviceModel = 8;</code>
     */
    public Builder mergeDeviceModel(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (deviceModelBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          deviceModel_ != null &&
          deviceModel_ != com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance()) {
          getDeviceModelBuilder().mergeFrom(value);
        } else {
          deviceModel_ = value;
        }
      } else {
        deviceModelBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString deviceModel = 8;</code>
     */
    public Builder clearDeviceModel() {
      bitField0_ = (bitField0_ & ~0x00000080);
      deviceModel_ = null;
      if (deviceModelBuilder_ != null) {
        deviceModelBuilder_.dispose();
        deviceModelBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString deviceModel = 8;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString.Builder getDeviceModelBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getDeviceModelFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableString deviceModel = 8;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getDeviceModelOrBuilder() {
      if (deviceModelBuilder_ != null) {
        return deviceModelBuilder_.getMessageOrBuilder();
      } else {
        return deviceModel_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : deviceModel_;
      }
    }
    /**
     * <code>.NullableString deviceModel = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> 
        getDeviceModelFieldBuilder() {
      if (deviceModelBuilder_ == null) {
        deviceModelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder>(
                getDeviceModel(),
                getParentForChildren(),
                isClean());
        deviceModel_ = null;
      }
      return deviceModelBuilder_;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableCustomData customData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableCustomData, com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder, com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder> customDataBuilder_;
    /**
     * <code>.NullableCustomData customData = 9;</code>
     * @return Whether the customData field is set.
     */
    public boolean hasCustomData() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.NullableCustomData customData = 9;</code>
     * @return The customData.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableCustomData getCustomData() {
      if (customDataBuilder_ == null) {
        return customData_ == null ? com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance() : customData_;
      } else {
        return customDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableCustomData customData = 9;</code>
     */
    public Builder setCustomData(com.devcycle.sdk.server.local.protobuf.NullableCustomData value) {
      if (customDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        customData_ = value;
      } else {
        customDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableCustomData customData = 9;</code>
     */
    public Builder setCustomData(
        com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder builderForValue) {
      if (customDataBuilder_ == null) {
        customData_ = builderForValue.build();
      } else {
        customDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableCustomData customData = 9;</code>
     */
    public Builder mergeCustomData(com.devcycle.sdk.server.local.protobuf.NullableCustomData value) {
      if (customDataBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          customData_ != null &&
          customData_ != com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance()) {
          getCustomDataBuilder().mergeFrom(value);
        } else {
          customData_ = value;
        }
      } else {
        customDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableCustomData customData = 9;</code>
     */
    public Builder clearCustomData() {
      bitField0_ = (bitField0_ & ~0x00000100);
      customData_ = null;
      if (customDataBuilder_ != null) {
        customDataBuilder_.dispose();
        customDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableCustomData customData = 9;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder getCustomDataBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getCustomDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableCustomData customData = 9;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder getCustomDataOrBuilder() {
      if (customDataBuilder_ != null) {
        return customDataBuilder_.getMessageOrBuilder();
      } else {
        return customData_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance() : customData_;
      }
    }
    /**
     * <code>.NullableCustomData customData = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableCustomData, com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder, com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder> 
        getCustomDataFieldBuilder() {
      if (customDataBuilder_ == null) {
        customDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableCustomData, com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder, com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder>(
                getCustomData(),
                getParentForChildren(),
                isClean());
        customData_ = null;
      }
      return customDataBuilder_;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableCustomData privateCustomData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableCustomData, com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder, com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder> privateCustomDataBuilder_;
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     * @return Whether the privateCustomData field is set.
     */
    public boolean hasPrivateCustomData() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     * @return The privateCustomData.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableCustomData getPrivateCustomData() {
      if (privateCustomDataBuilder_ == null) {
        return privateCustomData_ == null ? com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance() : privateCustomData_;
      } else {
        return privateCustomDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     */
    public Builder setPrivateCustomData(com.devcycle.sdk.server.local.protobuf.NullableCustomData value) {
      if (privateCustomDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        privateCustomData_ = value;
      } else {
        privateCustomDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     */
    public Builder setPrivateCustomData(
        com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder builderForValue) {
      if (privateCustomDataBuilder_ == null) {
        privateCustomData_ = builderForValue.build();
      } else {
        privateCustomDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     */
    public Builder mergePrivateCustomData(com.devcycle.sdk.server.local.protobuf.NullableCustomData value) {
      if (privateCustomDataBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          privateCustomData_ != null &&
          privateCustomData_ != com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance()) {
          getPrivateCustomDataBuilder().mergeFrom(value);
        } else {
          privateCustomData_ = value;
        }
      } else {
        privateCustomDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     */
    public Builder clearPrivateCustomData() {
      bitField0_ = (bitField0_ & ~0x00000200);
      privateCustomData_ = null;
      if (privateCustomDataBuilder_ != null) {
        privateCustomDataBuilder_.dispose();
        privateCustomDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder getPrivateCustomDataBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getPrivateCustomDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder getPrivateCustomDataOrBuilder() {
      if (privateCustomDataBuilder_ != null) {
        return privateCustomDataBuilder_.getMessageOrBuilder();
      } else {
        return privateCustomData_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance() : privateCustomData_;
      }
    }
    /**
     * <code>.NullableCustomData privateCustomData = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableCustomData, com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder, com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder> 
        getPrivateCustomDataFieldBuilder() {
      if (privateCustomDataBuilder_ == null) {
        privateCustomDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableCustomData, com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder, com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder>(
                getPrivateCustomData(),
                getParentForChildren(),
                isClean());
        privateCustomData_ = null;
      }
      return privateCustomDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DVCUser_PB)
  }

  // @@protoc_insertion_point(class_scope:DVCUser_PB)
  private static final com.devcycle.sdk.server.local.protobuf.DVCUser_PB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.devcycle.sdk.server.local.protobuf.DVCUser_PB();
  }

  public static com.devcycle.sdk.server.local.protobuf.DVCUser_PB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DVCUser_PB>
      PARSER = new com.google.protobuf.AbstractParser<DVCUser_PB>() {
    @java.lang.Override
    public DVCUser_PB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DVCUser_PB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DVCUser_PB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.DVCUser_PB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

