// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

public interface DVCUser_PBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DVCUser_PB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.NullableString email = 2;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>.NullableString email = 2;</code>
   * @return The email.
   */
  com.devcycle.sdk.server.local.protobuf.NullableString getEmail();
  /**
   * <code>.NullableString email = 2;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getEmailOrBuilder();

  /**
   * <code>.NullableString name = 3;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.NullableString name = 3;</code>
   * @return The name.
   */
  com.devcycle.sdk.server.local.protobuf.NullableString getName();
  /**
   * <code>.NullableString name = 3;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getNameOrBuilder();

  /**
   * <code>.NullableString language = 4;</code>
   * @return Whether the language field is set.
   */
  boolean hasLanguage();
  /**
   * <code>.NullableString language = 4;</code>
   * @return The language.
   */
  com.devcycle.sdk.server.local.protobuf.NullableString getLanguage();
  /**
   * <code>.NullableString language = 4;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getLanguageOrBuilder();

  /**
   * <code>.NullableString country = 5;</code>
   * @return Whether the country field is set.
   */
  boolean hasCountry();
  /**
   * <code>.NullableString country = 5;</code>
   * @return The country.
   */
  com.devcycle.sdk.server.local.protobuf.NullableString getCountry();
  /**
   * <code>.NullableString country = 5;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getCountryOrBuilder();

  /**
   * <code>.NullableDouble appBuild = 6;</code>
   * @return Whether the appBuild field is set.
   */
  boolean hasAppBuild();
  /**
   * <code>.NullableDouble appBuild = 6;</code>
   * @return The appBuild.
   */
  com.devcycle.sdk.server.local.protobuf.NullableDouble getAppBuild();
  /**
   * <code>.NullableDouble appBuild = 6;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableDoubleOrBuilder getAppBuildOrBuilder();

  /**
   * <code>.NullableString appVersion = 7;</code>
   * @return Whether the appVersion field is set.
   */
  boolean hasAppVersion();
  /**
   * <code>.NullableString appVersion = 7;</code>
   * @return The appVersion.
   */
  com.devcycle.sdk.server.local.protobuf.NullableString getAppVersion();
  /**
   * <code>.NullableString appVersion = 7;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getAppVersionOrBuilder();

  /**
   * <code>.NullableString deviceModel = 8;</code>
   * @return Whether the deviceModel field is set.
   */
  boolean hasDeviceModel();
  /**
   * <code>.NullableString deviceModel = 8;</code>
   * @return The deviceModel.
   */
  com.devcycle.sdk.server.local.protobuf.NullableString getDeviceModel();
  /**
   * <code>.NullableString deviceModel = 8;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getDeviceModelOrBuilder();

  /**
   * <code>.NullableCustomData customData = 9;</code>
   * @return Whether the customData field is set.
   */
  boolean hasCustomData();
  /**
   * <code>.NullableCustomData customData = 9;</code>
   * @return The customData.
   */
  com.devcycle.sdk.server.local.protobuf.NullableCustomData getCustomData();
  /**
   * <code>.NullableCustomData customData = 9;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder getCustomDataOrBuilder();

  /**
   * <code>.NullableCustomData privateCustomData = 10;</code>
   * @return Whether the privateCustomData field is set.
   */
  boolean hasPrivateCustomData();
  /**
   * <code>.NullableCustomData privateCustomData = 10;</code>
   * @return The privateCustomData.
   */
  com.devcycle.sdk.server.local.protobuf.NullableCustomData getPrivateCustomData();
  /**
   * <code>.NullableCustomData privateCustomData = 10;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder getPrivateCustomDataOrBuilder();
}
