// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

/**
 * Protobuf type {@code NullableCustomData}
 */
public final class NullableCustomData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NullableCustomData)
    NullableCustomDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NullableCustomData.newBuilder() to construct.
  private NullableCustomData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NullableCustomData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NullableCustomData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_NullableCustomData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetValue();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_NullableCustomData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.devcycle.sdk.server.local.protobuf.NullableCustomData.class, com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder.class);
  }

  public static final int VALUE_FIELD_NUMBER = 1;
  private static final class ValueDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>newDefaultInstance(
                com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_NullableCustomData_ValueEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.devcycle.sdk.server.local.protobuf.CustomDataValue.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> value_;
  private com.google.protobuf.MapField<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>
  internalGetValue() {
    if (value_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ValueDefaultEntryHolder.defaultEntry);
    }
    return value_;
  }
  public int getValueCount() {
    return internalGetValue().getMap().size();
  }
  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  @java.lang.Override
  public boolean containsValue(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetValue().getMap().containsKey(key);
  }
  /**
   * Use {@link #getValueMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> getValue() {
    return getValueMap();
  }
  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> getValueMap() {
    return internalGetValue().getMap();
  }
  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
com.devcycle.sdk.server.local.protobuf.CustomDataValue getValueOrDefault(
      java.lang.String key,
      /* nullable */
com.devcycle.sdk.server.local.protobuf.CustomDataValue defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> map =
        internalGetValue().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.CustomDataValue getValueOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> map =
        internalGetValue().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ISNULL_FIELD_NUMBER = 2;
  private boolean isNull_ = false;
  /**
   * <code>bool isNull = 2;</code>
   * @return The isNull.
   */
  @java.lang.Override
  public boolean getIsNull() {
    return isNull_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetValue(),
        ValueDefaultEntryHolder.defaultEntry,
        1);
    if (isNull_ != false) {
      output.writeBool(2, isNull_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> entry
         : internalGetValue().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>
      value__ = ValueDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, value__);
    }
    if (isNull_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isNull_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.devcycle.sdk.server.local.protobuf.NullableCustomData)) {
      return super.equals(obj);
    }
    com.devcycle.sdk.server.local.protobuf.NullableCustomData other = (com.devcycle.sdk.server.local.protobuf.NullableCustomData) obj;

    if (!internalGetValue().equals(
        other.internalGetValue())) return false;
    if (getIsNull()
        != other.getIsNull()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetValue().getMap().isEmpty()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetValue().hashCode();
    }
    hash = (37 * hash) + ISNULL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsNull());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.devcycle.sdk.server.local.protobuf.NullableCustomData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NullableCustomData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NullableCustomData)
      com.devcycle.sdk.server.local.protobuf.NullableCustomDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_NullableCustomData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetValue();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableValue();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_NullableCustomData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.devcycle.sdk.server.local.protobuf.NullableCustomData.class, com.devcycle.sdk.server.local.protobuf.NullableCustomData.Builder.class);
    }

    // Construct using com.devcycle.sdk.server.local.protobuf.NullableCustomData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableValue().clear();
      isNull_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_NullableCustomData_descriptor;
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.NullableCustomData getDefaultInstanceForType() {
      return com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance();
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.NullableCustomData build() {
      com.devcycle.sdk.server.local.protobuf.NullableCustomData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.NullableCustomData buildPartial() {
      com.devcycle.sdk.server.local.protobuf.NullableCustomData result = new com.devcycle.sdk.server.local.protobuf.NullableCustomData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.devcycle.sdk.server.local.protobuf.NullableCustomData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.value_ = internalGetValue();
        result.value_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isNull_ = isNull_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.devcycle.sdk.server.local.protobuf.NullableCustomData) {
        return mergeFrom((com.devcycle.sdk.server.local.protobuf.NullableCustomData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.devcycle.sdk.server.local.protobuf.NullableCustomData other) {
      if (other == com.devcycle.sdk.server.local.protobuf.NullableCustomData.getDefaultInstance()) return this;
      internalGetMutableValue().mergeFrom(
          other.internalGetValue());
      bitField0_ |= 0x00000001;
      if (other.getIsNull() != false) {
        setIsNull(other.getIsNull());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>
              value__ = input.readMessage(
                  ValueDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableValue().getMutableMap().put(
                  value__.getKey(), value__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isNull_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> value_;
    private com.google.protobuf.MapField<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>
        internalGetValue() {
      if (value_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValueDefaultEntryHolder.defaultEntry);
      }
      return value_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>
        internalGetMutableValue() {
      if (value_ == null) {
        value_ = com.google.protobuf.MapField.newMapField(
            ValueDefaultEntryHolder.defaultEntry);
      }
      if (!value_.isMutable()) {
        value_ = value_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return value_;
    }
    public int getValueCount() {
      return internalGetValue().getMap().size();
    }
    /**
     * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
     */
    @java.lang.Override
    public boolean containsValue(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetValue().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValueMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> getValue() {
      return getValueMap();
    }
    /**
     * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> getValueMap() {
      return internalGetValue().getMap();
    }
    /**
     * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.devcycle.sdk.server.local.protobuf.CustomDataValue getValueOrDefault(
        java.lang.String key,
        /* nullable */
com.devcycle.sdk.server.local.protobuf.CustomDataValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> map =
          internalGetValue().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
     */
    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.CustomDataValue getValueOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> map =
          internalGetValue().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableValue().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
     */
    public Builder removeValue(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableValue().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>
        getMutableValue() {
      bitField0_ |= 0x00000001;
      return internalGetMutableValue().getMutableMap();
    }
    /**
     * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
     */
    public Builder putValue(
        java.lang.String key,
        com.devcycle.sdk.server.local.protobuf.CustomDataValue value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableValue().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
     */
    public Builder putAllValue(
        java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue> values) {
      internalGetMutableValue().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }

    private boolean isNull_ ;
    /**
     * <code>bool isNull = 2;</code>
     * @return The isNull.
     */
    @java.lang.Override
    public boolean getIsNull() {
      return isNull_;
    }
    /**
     * <code>bool isNull = 2;</code>
     * @param value The isNull to set.
     * @return This builder for chaining.
     */
    public Builder setIsNull(boolean value) {
      
      isNull_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool isNull = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsNull() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isNull_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NullableCustomData)
  }

  // @@protoc_insertion_point(class_scope:NullableCustomData)
  private static final com.devcycle.sdk.server.local.protobuf.NullableCustomData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.devcycle.sdk.server.local.protobuf.NullableCustomData();
  }

  public static com.devcycle.sdk.server.local.protobuf.NullableCustomData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NullableCustomData>
      PARSER = new com.google.protobuf.AbstractParser<NullableCustomData>() {
    @java.lang.Override
    public NullableCustomData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NullableCustomData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NullableCustomData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableCustomData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

