// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

public interface NullableDoubleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NullableDouble)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double value = 1;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>bool isNull = 2;</code>
   * @return The isNull.
   */
  boolean getIsNull();
}
