// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

public interface NullableCustomDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NullableCustomData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  int getValueCount();
  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  boolean containsValue(
      java.lang.String key);
  /**
   * Use {@link #getValueMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>
  getValue();
  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  java.util.Map<java.lang.String, com.devcycle.sdk.server.local.protobuf.CustomDataValue>
  getValueMap();
  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  /* nullable */
com.devcycle.sdk.server.local.protobuf.CustomDataValue getValueOrDefault(
      java.lang.String key,
      /* nullable */
com.devcycle.sdk.server.local.protobuf.CustomDataValue defaultValue);
  /**
   * <code>map&lt;string, .CustomDataValue&gt; value = 1;</code>
   */
  com.devcycle.sdk.server.local.protobuf.CustomDataValue getValueOrThrow(
      java.lang.String key);

  /**
   * <code>bool isNull = 2;</code>
   * @return The isNull.
   */
  boolean getIsNull();
}
