// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

public interface SDKVariable_PBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SDKVariable_PB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string _id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string _id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.VariableType_PB type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.VariableType_PB type = 2;</code>
   * @return The type.
   */
  com.devcycle.sdk.server.local.protobuf.VariableType_PB getType();

  /**
   * <code>string key = 3;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 3;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>bool boolValue = 4;</code>
   * @return The boolValue.
   */
  boolean getBoolValue();

  /**
   * <code>double doubleValue = 5;</code>
   * @return The doubleValue.
   */
  double getDoubleValue();

  /**
   * <code>string stringValue = 6;</code>
   * @return The stringValue.
   */
  java.lang.String getStringValue();
  /**
   * <code>string stringValue = 6;</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>.NullableString evalReason = 7;</code>
   * @return Whether the evalReason field is set.
   */
  boolean hasEvalReason();
  /**
   * <code>.NullableString evalReason = 7;</code>
   * @return The evalReason.
   */
  com.devcycle.sdk.server.local.protobuf.NullableString getEvalReason();
  /**
   * <code>.NullableString evalReason = 7;</code>
   */
  com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getEvalReasonOrBuilder();
}
