// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

/**
 * Protobuf type {@code SDKVariable_PB}
 */
public final class SDKVariable_PB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SDKVariable_PB)
    SDKVariable_PBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SDKVariable_PB.newBuilder() to construct.
  private SDKVariable_PB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SDKVariable_PB() {
    Id_ = "";
    type_ = 0;
    key_ = "";
    stringValue_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SDKVariable_PB();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_SDKVariable_PB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_SDKVariable_PB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.devcycle.sdk.server.local.protobuf.SDKVariable_PB.class, com.devcycle.sdk.server.local.protobuf.SDKVariable_PB.Builder.class);
  }

  public static final int _ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object Id_ = "";
  /**
   * <code>string _id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = Id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      Id_ = s;
      return s;
    }
  }
  /**
   * <code>string _id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = Id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      Id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_ = 0;
  /**
   * <code>.VariableType_PB type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.VariableType_PB type = 2;</code>
   * @return The type.
   */
  @java.lang.Override public com.devcycle.sdk.server.local.protobuf.VariableType_PB getType() {
    com.devcycle.sdk.server.local.protobuf.VariableType_PB result = com.devcycle.sdk.server.local.protobuf.VariableType_PB.forNumber(type_);
    return result == null ? com.devcycle.sdk.server.local.protobuf.VariableType_PB.UNRECOGNIZED : result;
  }

  public static final int KEY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object key_ = "";
  /**
   * <code>string key = 3;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 3;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOLVALUE_FIELD_NUMBER = 4;
  private boolean boolValue_ = false;
  /**
   * <code>bool boolValue = 4;</code>
   * @return The boolValue.
   */
  @java.lang.Override
  public boolean getBoolValue() {
    return boolValue_;
  }

  public static final int DOUBLEVALUE_FIELD_NUMBER = 5;
  private double doubleValue_ = 0D;
  /**
   * <code>double doubleValue = 5;</code>
   * @return The doubleValue.
   */
  @java.lang.Override
  public double getDoubleValue() {
    return doubleValue_;
  }

  public static final int STRINGVALUE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stringValue_ = "";
  /**
   * <code>string stringValue = 6;</code>
   * @return The stringValue.
   */
  @java.lang.Override
  public java.lang.String getStringValue() {
    java.lang.Object ref = stringValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stringValue_ = s;
      return s;
    }
  }
  /**
   * <code>string stringValue = 6;</code>
   * @return The bytes for stringValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.Object ref = stringValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stringValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVALREASON_FIELD_NUMBER = 7;
  private com.devcycle.sdk.server.local.protobuf.NullableString evalReason_;
  /**
   * <code>.NullableString evalReason = 7;</code>
   * @return Whether the evalReason field is set.
   */
  @java.lang.Override
  public boolean hasEvalReason() {
    return evalReason_ != null;
  }
  /**
   * <code>.NullableString evalReason = 7;</code>
   * @return The evalReason.
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableString getEvalReason() {
    return evalReason_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : evalReason_;
  }
  /**
   * <code>.NullableString evalReason = 7;</code>
   */
  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getEvalReasonOrBuilder() {
    return evalReason_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : evalReason_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(Id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, Id_);
    }
    if (type_ != com.devcycle.sdk.server.local.protobuf.VariableType_PB.Boolean.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, key_);
    }
    if (boolValue_ != false) {
      output.writeBool(4, boolValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(doubleValue_) != 0) {
      output.writeDouble(5, doubleValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringValue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stringValue_);
    }
    if (evalReason_ != null) {
      output.writeMessage(7, getEvalReason());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(Id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, Id_);
    }
    if (type_ != com.devcycle.sdk.server.local.protobuf.VariableType_PB.Boolean.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, key_);
    }
    if (boolValue_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, boolValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(doubleValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, doubleValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringValue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, stringValue_);
    }
    if (evalReason_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getEvalReason());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.devcycle.sdk.server.local.protobuf.SDKVariable_PB)) {
      return super.equals(obj);
    }
    com.devcycle.sdk.server.local.protobuf.SDKVariable_PB other = (com.devcycle.sdk.server.local.protobuf.SDKVariable_PB) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (type_ != other.type_) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (getBoolValue()
        != other.getBoolValue()) return false;
    if (java.lang.Double.doubleToLongBits(getDoubleValue())
        != java.lang.Double.doubleToLongBits(
            other.getDoubleValue())) return false;
    if (!getStringValue()
        .equals(other.getStringValue())) return false;
    if (hasEvalReason() != other.hasEvalReason()) return false;
    if (hasEvalReason()) {
      if (!getEvalReason()
          .equals(other.getEvalReason())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + _ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    hash = (37 * hash) + BOOLVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolValue());
    hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDoubleValue()));
    hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getStringValue().hashCode();
    if (hasEvalReason()) {
      hash = (37 * hash) + EVALREASON_FIELD_NUMBER;
      hash = (53 * hash) + getEvalReason().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.devcycle.sdk.server.local.protobuf.SDKVariable_PB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SDKVariable_PB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SDKVariable_PB)
      com.devcycle.sdk.server.local.protobuf.SDKVariable_PBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_SDKVariable_PB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_SDKVariable_PB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.devcycle.sdk.server.local.protobuf.SDKVariable_PB.class, com.devcycle.sdk.server.local.protobuf.SDKVariable_PB.Builder.class);
    }

    // Construct using com.devcycle.sdk.server.local.protobuf.SDKVariable_PB.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      Id_ = "";
      type_ = 0;
      key_ = "";
      boolValue_ = false;
      doubleValue_ = 0D;
      stringValue_ = "";
      evalReason_ = null;
      if (evalReasonBuilder_ != null) {
        evalReasonBuilder_.dispose();
        evalReasonBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.internal_static_SDKVariable_PB_descriptor;
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.SDKVariable_PB getDefaultInstanceForType() {
      return com.devcycle.sdk.server.local.protobuf.SDKVariable_PB.getDefaultInstance();
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.SDKVariable_PB build() {
      com.devcycle.sdk.server.local.protobuf.SDKVariable_PB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.SDKVariable_PB buildPartial() {
      com.devcycle.sdk.server.local.protobuf.SDKVariable_PB result = new com.devcycle.sdk.server.local.protobuf.SDKVariable_PB(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.devcycle.sdk.server.local.protobuf.SDKVariable_PB result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.Id_ = Id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.key_ = key_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.boolValue_ = boolValue_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.doubleValue_ = doubleValue_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.stringValue_ = stringValue_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.evalReason_ = evalReasonBuilder_ == null
            ? evalReason_
            : evalReasonBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.devcycle.sdk.server.local.protobuf.SDKVariable_PB) {
        return mergeFrom((com.devcycle.sdk.server.local.protobuf.SDKVariable_PB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.devcycle.sdk.server.local.protobuf.SDKVariable_PB other) {
      if (other == com.devcycle.sdk.server.local.protobuf.SDKVariable_PB.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        Id_ = other.Id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getBoolValue() != false) {
        setBoolValue(other.getBoolValue());
      }
      if (other.getDoubleValue() != 0D) {
        setDoubleValue(other.getDoubleValue());
      }
      if (!other.getStringValue().isEmpty()) {
        stringValue_ = other.stringValue_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasEvalReason()) {
        mergeEvalReason(other.getEvalReason());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              key_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              boolValue_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 41: {
              doubleValue_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 50: {
              stringValue_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getEvalReasonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object Id_ = "";
    /**
     * <code>string _id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = Id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        Id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string _id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = Id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        Id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string _id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      Id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string _id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      Id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string _id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      Id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.VariableType_PB type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.VariableType_PB type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.VariableType_PB type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.devcycle.sdk.server.local.protobuf.VariableType_PB getType() {
      com.devcycle.sdk.server.local.protobuf.VariableType_PB result = com.devcycle.sdk.server.local.protobuf.VariableType_PB.forNumber(type_);
      return result == null ? com.devcycle.sdk.server.local.protobuf.VariableType_PB.UNRECOGNIZED : result;
    }
    /**
     * <code>.VariableType_PB type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.devcycle.sdk.server.local.protobuf.VariableType_PB value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.VariableType_PB type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 3;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 3;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 3;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      key_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      key_ = getDefaultInstance().getKey();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string key = 3;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      key_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean boolValue_ ;
    /**
     * <code>bool boolValue = 4;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      return boolValue_;
    }
    /**
     * <code>bool boolValue = 4;</code>
     * @param value The boolValue to set.
     * @return This builder for chaining.
     */
    public Builder setBoolValue(boolean value) {
      
      boolValue_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool boolValue = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolValue() {
      bitField0_ = (bitField0_ & ~0x00000008);
      boolValue_ = false;
      onChanged();
      return this;
    }

    private double doubleValue_ ;
    /**
     * <code>double doubleValue = 5;</code>
     * @return The doubleValue.
     */
    @java.lang.Override
    public double getDoubleValue() {
      return doubleValue_;
    }
    /**
     * <code>double doubleValue = 5;</code>
     * @param value The doubleValue to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleValue(double value) {
      
      doubleValue_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double doubleValue = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      doubleValue_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object stringValue_ = "";
    /**
     * <code>string stringValue = 6;</code>
     * @return The stringValue.
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stringValue = 6;</code>
     * @return The bytes for stringValue.
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stringValue = 6;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stringValue_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string stringValue = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      stringValue_ = getDefaultInstance().getStringValue();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string stringValue = 6;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stringValue_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.devcycle.sdk.server.local.protobuf.NullableString evalReason_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> evalReasonBuilder_;
    /**
     * <code>.NullableString evalReason = 7;</code>
     * @return Whether the evalReason field is set.
     */
    public boolean hasEvalReason() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.NullableString evalReason = 7;</code>
     * @return The evalReason.
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString getEvalReason() {
      if (evalReasonBuilder_ == null) {
        return evalReason_ == null ? com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : evalReason_;
      } else {
        return evalReasonBuilder_.getMessage();
      }
    }
    /**
     * <code>.NullableString evalReason = 7;</code>
     */
    public Builder setEvalReason(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (evalReasonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        evalReason_ = value;
      } else {
        evalReasonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString evalReason = 7;</code>
     */
    public Builder setEvalReason(
        com.devcycle.sdk.server.local.protobuf.NullableString.Builder builderForValue) {
      if (evalReasonBuilder_ == null) {
        evalReason_ = builderForValue.build();
      } else {
        evalReasonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString evalReason = 7;</code>
     */
    public Builder mergeEvalReason(com.devcycle.sdk.server.local.protobuf.NullableString value) {
      if (evalReasonBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          evalReason_ != null &&
          evalReason_ != com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance()) {
          getEvalReasonBuilder().mergeFrom(value);
        } else {
          evalReason_ = value;
        }
      } else {
        evalReasonBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString evalReason = 7;</code>
     */
    public Builder clearEvalReason() {
      bitField0_ = (bitField0_ & ~0x00000040);
      evalReason_ = null;
      if (evalReasonBuilder_ != null) {
        evalReasonBuilder_.dispose();
        evalReasonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.NullableString evalReason = 7;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableString.Builder getEvalReasonBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getEvalReasonFieldBuilder().getBuilder();
    }
    /**
     * <code>.NullableString evalReason = 7;</code>
     */
    public com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder getEvalReasonOrBuilder() {
      if (evalReasonBuilder_ != null) {
        return evalReasonBuilder_.getMessageOrBuilder();
      } else {
        return evalReason_ == null ?
            com.devcycle.sdk.server.local.protobuf.NullableString.getDefaultInstance() : evalReason_;
      }
    }
    /**
     * <code>.NullableString evalReason = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder> 
        getEvalReasonFieldBuilder() {
      if (evalReasonBuilder_ == null) {
        evalReasonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.devcycle.sdk.server.local.protobuf.NullableString, com.devcycle.sdk.server.local.protobuf.NullableString.Builder, com.devcycle.sdk.server.local.protobuf.NullableStringOrBuilder>(
                getEvalReason(),
                getParentForChildren(),
                isClean());
        evalReason_ = null;
      }
      return evalReasonBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SDKVariable_PB)
  }

  // @@protoc_insertion_point(class_scope:SDKVariable_PB)
  private static final com.devcycle.sdk.server.local.protobuf.SDKVariable_PB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.devcycle.sdk.server.local.protobuf.SDKVariable_PB();
  }

  public static com.devcycle.sdk.server.local.protobuf.SDKVariable_PB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SDKVariable_PB>
      PARSER = new com.google.protobuf.AbstractParser<SDKVariable_PB>() {
    @java.lang.Override
    public SDKVariable_PB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SDKVariable_PB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SDKVariable_PB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.devcycle.sdk.server.local.protobuf.SDKVariable_PB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

