// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

public interface VariableForUserParams_PBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VariableForUserParams_PB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sdkKey = 1;</code>
   * @return The sdkKey.
   */
  java.lang.String getSdkKey();
  /**
   * <code>string sdkKey = 1;</code>
   * @return The bytes for sdkKey.
   */
  com.google.protobuf.ByteString
      getSdkKeyBytes();

  /**
   * <code>string variableKey = 2;</code>
   * @return The variableKey.
   */
  java.lang.String getVariableKey();
  /**
   * <code>string variableKey = 2;</code>
   * @return The bytes for variableKey.
   */
  com.google.protobuf.ByteString
      getVariableKeyBytes();

  /**
   * <code>.VariableType_PB variableType = 3;</code>
   * @return The enum numeric value on the wire for variableType.
   */
  int getVariableTypeValue();
  /**
   * <code>.VariableType_PB variableType = 3;</code>
   * @return The variableType.
   */
  com.devcycle.sdk.server.local.protobuf.VariableType_PB getVariableType();

  /**
   * <code>.DVCUser_PB user = 4;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.DVCUser_PB user = 4;</code>
   * @return The user.
   */
  com.devcycle.sdk.server.local.protobuf.DVCUser_PB getUser();
  /**
   * <code>.DVCUser_PB user = 4;</code>
   */
  com.devcycle.sdk.server.local.protobuf.DVCUser_PBOrBuilder getUserOrBuilder();

  /**
   * <code>bool shouldTrackEvent = 5;</code>
   * @return The shouldTrackEvent.
   */
  boolean getShouldTrackEvent();
}
