// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variableForUserParams.proto

package com.devcycle.sdk.server.local.protobuf;

/**
 * Protobuf enum {@code VariableType_PB}
 */
public enum VariableType_PB
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Boolean = 0;</code>
   */
  Boolean(0),
  /**
   * <code>Number = 1;</code>
   */
  Number(1),
  /**
   * <code>String = 2;</code>
   */
  String(2),
  /**
   * <code>JSON = 3;</code>
   */
  JSON(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Boolean = 0;</code>
   */
  public static final int Boolean_VALUE = 0;
  /**
   * <code>Number = 1;</code>
   */
  public static final int Number_VALUE = 1;
  /**
   * <code>String = 2;</code>
   */
  public static final int String_VALUE = 2;
  /**
   * <code>JSON = 3;</code>
   */
  public static final int JSON_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VariableType_PB valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VariableType_PB forNumber(int value) {
    switch (value) {
      case 0: return Boolean;
      case 1: return Number;
      case 2: return String;
      case 3: return JSON;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VariableType_PB>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VariableType_PB> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VariableType_PB>() {
          public VariableType_PB findValueByNumber(int number) {
            return VariableType_PB.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.devcycle.sdk.server.local.protobuf.VariableForUserParams.getDescriptor().getEnumTypes().get(0);
  }

  private static final VariableType_PB[] VALUES = values();

  public static VariableType_PB valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VariableType_PB(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:VariableType_PB)
}

