name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Prerelease"
        required: true
        default: false
        type: boolean
      draft:
        description: "Draft"
        required: true
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  release:
    name: Version Bump and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          fetch-depth: 0

      - name: Get latest non-prerelease release
        id: latestrelease
        uses: cardinalby/git-get-release-action@v1
        with:
          latest: true
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: semverbump
        uses: WyriHaximus/github-action-next-semvers@v1.2.1
        with:
          version: ${{ steps.latestrelease.outputs.tag_name }}

      - name: Update Version in code
        run: |
          sed -i "s/^version = \"[0-9].[0-9].[0-9]\"/version = \"${{steps.semverbump.outputs.patch}}\"/g" build.gradle
          sed -i "s/private String sdkVersion = \"[0-9]\.[0-9]\.[0-9]\";/private String sdkVersion = \"${{steps.semverbump.outputs.patch}}\";/g" src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
          sed -i "s/java-server-sdk:[0-9]\.[0-9]\.[0-9]/java-server-sdk:${{steps.semverbump.outputs.patch}}/g" ./example-cloud/build.gradle
          sed -i "s/java-server-sdk:[0-9]\.[0-9]\.[0-9]/java-server-sdk:${{steps.semverbump.outputs.patch}}/g" ./example-local/build.gradle
          sed -i "s/<java\.server\.sdk\.version>[0-9]\.[0-9]\.[0-9]<\/java\.server\.sdk\.version>/<java.server.sdk.version>${{steps.semverbump.outputs.patch}}<\/java.server.sdk.version>/g" ./benchmark/pom.xml
          sed -i "s/<version>[0-9]\.[0-9]\.[0-9]<\/version>/<version>${{steps.semverbump.outputs.patch}}<\/version>/g" ./README.md
          sed -i "s/java-server-sdk:[0-9]\.[0-9]\.[0-9]/java-server-sdk:${{steps.semverbump.outputs.patch}}/g" ./README.md

      - name: Commit version change
        run: |
          git config --global user.email "github-tracker-bot@taplytics.com"
          git config --global user.name "DevCycle Automation"
          git add ./build.gradle
          git add ./src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
          git add ./example-cloud/build.gradle
          git add ./example-local/build.gradle
          git add ./benchmark/pom.xml
          git add ./README.md
          git commit -m "Release ${{steps.semverbump.outputs.patch}}"

      - name: Push version change
        run: |
          git push origin HEAD:main
        if: inputs.prerelease != true && inputs.draft != true

      - name: Push version change (prerelease)
        run: |
          git branch --force --track ${BRANCH}
          git push origin ${BRANCH}
        env:
          BRANCH: prerelease-${{ steps.semverbump.outputs.patch }}
        if: inputs.prerelease == true && inputs.draft != true

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'gradle'

      - name: Build and Publish To Sonatype
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishToSonatype

      - name: Close Sonatype Staging Repository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew findSonatypeStagingRepository closeSonatypeStagingRepository

      - name: Release Sonatype Staging Repository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew findSonatypeStagingRepository releaseSonatypeStagingRepository

      - name: Release SDK
        uses: DevCycleHQ/release-action/gh-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: ${{ github.event.inputs.draft }}
